language: php

# execute unit tests, integration test stubs and integration tests using legacy storage engine
env:
  global:
    - DB_NAME="testdb"

matrix:
  # mark as finished before allow_failures are run
  fast_finish: true
  # misc nighlty tests we keep an eye on and aim to fix closer to stable versions
#  allow_failures:
#    - php: hhvm
#      env: TEST_CONFIG="phpunit.xml"
  include:
    - php: 5.5
      env: TEST_CONFIG="phpunit-integration-legacy.xml" DB="mysql" DATABASE="mysql://root@localhost/$DB_NAME"
    - php: 5.6
      env: TEST_CONFIG="phpunit-integration-legacy.xml" DB="mysql" DATABASE="mysql://root@localhost/$DB_NAME"
    - php: 7.0
      env: TEST_CONFIG="phpunit-integration-legacy.xml" DB="mysql" DATABASE="mysql://root@localhost/$DB_NAME"



# test only master (+ Pull requests)
branches:
  only:
    - master
    - "6.1"

# setup requirements for running unit/integration/behat tests
before_script:
  # Prepare system
  - if [ "$TEST_CONFIG" != "" ] ; then ./bin/.travis/prepare_unittest.sh ; fi
  - if [ "$BEHAT_OPTS" != "" ] ; then ./bin/.travis/prepare_behat.sh ; fi
  - if [ "$REST_TEST_CONFIG" != "" ] ; then ./bin/.travis/prepare_behat.sh ; echo pwd; cd "$HOME/build/ezplatform/vendor/ezsystems/ezpublish-kernel"; ./bin/.travis/prepare_rest_functional_tests.sh; fi
  # Detecting timezone issues by testing on random timezone
  - TEST_TIMEZONES=("America/New_York" "Asia/Calcutta" "UTC")
  - TEST_TIMEZONE=${TEST_TIMEZONES["`shuf -i 0-2 -n 1`"]}

# execute phpunit or behat as the script command
script:
  - if [ "$TEST_CONFIG" != "" ] ; then php -d date.timezone=$TEST_TIMEZONE -d memory_limit=-1 vendor/bin/phpunit -c $TEST_CONFIG --filter UserServiceTest::testLoadUserByCredentialsThrowsNotFoundExceptionForUnknownLogin ; fi
  - if [ "$BEHAT_OPTS" != "" ] ; then cd "$HOME/build/ezplatform" && php bin/behat -vv $BEHAT_OPTS ; fi
  - if [ "$REST_TEST_CONFIG" != "" ] ; then cd "$HOME/build/ezplatform"; php -d date.timezone=$TEST_TIMEZONE -d memory_limit=-1 bin/phpunit -v vendor/ezsystems/ezpublish-kernel/eZ/Bundle/EzPublishRestBundle/Tests/Functional ; fi

# disable mail notifications
notifications:
  email: false

# reduce depth (history) of git checkout
git:
  depth: 30
